/**
 * Created by bala on 10/7/15.
 */

var ndEventLoopMonitor = require('./lib/event_loop_moitor/ndEventLoopMonitor.js');
var ndHeapGCMonitor = require('./lib/heap_gc_monitor/ndHeapGCMonitor.js');
var njstrace = require('./lib/njstrace/njsTrace');
var agentSetting = require("./lib/agent-setting");
var clientConn = require("./lib/client");
var path = require('path');
var util = require('./lib/util');
var fs = require('fs');
var instrumentationFile = path.join(path.resolve(__dirname),'/../../instrumentation.conf');

NJSInstrument.prototype.instrument = function instrument(filename)
{
    try
    {
        util.initializeLogger();

        agentSetting.readSettingFile();

        //In cluster mode, Instance filed will be generated by agent only in EXCLUSIVE mode in Shared mode, auto scale feature will be
        //used to generate instance by NDC

        if('EXCLUSIVE' === agentSetting.settingFileMode.toUpperCase() )
            agentSetting.isCluster();

        agentSetting.initAllMap();

        agentSetting.generateFPMask();

        njstrace.inject(null,instrumentationFile);

        require('./lib/nodetime/index').profile();

        process.nextTick(function(){
            try {
                clientConn.connectToServer();
            }
            catch(e){
                util.logger.warn(e);
            }
        },1000);


    }
    catch(err){
        console.log(err);
    }
};

function NJSInstrument()
{

}

module.exports = new NJSInstrument();